services:
  # Backend Service
  - type: web
    name: itinerary-backend
    env: python
    runtime: python-3.10.13
    buildCommand: |
      cd backend && 
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: |
      cd backend && 
      uvicorn server:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./itinerary.db
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        value: your-openai-api-key-here
      - key: DEBUG
        value: false
    healthCheckPath: /api/health
    
  # Optional: Static Site for Frontend (if not using Vercel)
  - type: static
    name: itinerary-frontend
    buildCommand: |
      cd frontend && 
      yarn install && 
      yarn build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://your-backend-service-name.onrender.com

# Database (if using Render's PostgreSQL - optional)
# databases:
#   - name: itinerary-postgres
#     databaseName: itinerary_management
#     user: itinerary_user